CREATE TABLE IF NOT EXISTS orders (
    id INT PRIMARY KEY AUTO_INCREMENT,
    customer_name VARCHAR(255) NOT NULL,
    total_amount DOUBLE NOT NULL,
    status ENUM('PENDING','SHIPPED','DELIVERED') NOT NULL DEFAULT 'PENDING',
    created_at DATETIME NOT NULL
);